### PR TITLE
fix build on kernel 6.2

### LINKED ISSUE #11: build error on 6.2
```
[...]/vtty/vtty.c: In function ‘vtmx_read’:
[...]/vtty/vtty.c:454:54: error: implicit declaration of function ‘kernel_termios_to_user_termios’ [-Werror=implicit-function-declaration]
  454 |                   copystatus = kernel_termios_to_user_termios((struct termios2 __user*)ptr, &port->oob_data.termios);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by christianrauch**
Fixes #11 .

### CODE REVIEW

**Comment by anszom** [comment]
thanks:)
